CRUD/CRUD/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace CRUD.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options):base(options)
        {
        }

        public DbSet<Caminhao> Caminhao { get; set; }
    }
}

CRUD/CRUD/Models/Caminhao.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;

namespace CRUD.Models
{
    public class Caminhao
    {
        [Key]
        [Required(ErrorMessage = "Informe a ID do caminhão.")]
        [Range(1, int.MaxValue, ErrorMessage = "O ID não pode ser nulo (0) ou um número negativo.")]
        [Display(Name ="ID do caminhão")]
        public int IdCaminhao { get; set; }

        [Required(ErrorMessage = "Informe o nome do caminhão.")]
        [Display(Name ="Nome do caminhão")]
        [StringLength(50, ErrorMessage = "Limite máximo de caracteres foi excedido (50).")]
        public string Nome { get; set; }

        [Display(Name = "Descrição do caminhão")]
        [StringLength(100, ErrorMessage = "Limite máximo de caracteres foi excedido (100).")]
        public string Descricao { get; set; }

        [Display(Name = "Data da criação")]
        [Required(ErrorMessage = "Informe a data de criação.")]
        [DataType(DataType.Date)]
        public DateTime DataCriacao { get; set; }

    }
}

CRUD/CRUD/Models/ErrorViewModel.cs
using System;

namespace CRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD/CRUD/Controllers/CaminhaoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using CRUD.Models;

namespace CRUD.Controllers
{
    public class CaminhaoController : Controller
    {

#region INTANCIANDO O BANCO DE DADOS
        private readonly ApplicationDbContext _database;

        public CaminhaoController(ApplicationDbContext context)
        {
            _database = context;
        }
        #endregion

#region VIEW INDEX
        public IActionResult Index()
        {
            var lista = _database.Caminhao.ToList(); // "lista" irá receber os dados da tabela pelo método "ToList"
            return View(lista); // retorna a view já com os dados atualizados
        }
        #endregion

#region VIEW DETAILS
        public async Task<IActionResult> Details(int id)
        {
            var detalhes = await _database.Caminhao.FindAsync(id);
            return View(detalhes);
        }
        #endregion

#region VIEW CREATE
        public IActionResult Create()
        {
            return View();
        }

        /* Quando a Action Create é acionada o método async irá fazer a validação do ID para evitar erros de duplicidade de ID
         * e após isso salvará os dados*/
        [HttpPost]
        public async Task<IActionResult> Create(Caminhao novo)
        {
            if (_database.Caminhao. Any(registro => registro.IdCaminhao == novo.IdCaminhao))
            {
                ModelState.AddModelError("IdCaminhao", "Esse ID já está registrado.");
                return View(novo);
            }
            if (ModelState.IsValid)
            {
                _database.Add(novo);
                await _database.SaveChangesAsync();
                return RedirectToAction("Index");
            }
                return View(novo);
        }
        #endregion

#region VIEW EDIT
        public async Task<IActionResult> Edit(int id) // "id" irá receber o ID do caminhão que cliclamos em Editar
        {
            var obterDetalhes = await _database.Caminhao.FindAsync(id); // "obterDetalhes" vai armazenar as informações que serão exibidas na view, conforme o valor do parâmetro informado no método FindAsync() 
            return View(obterDetalhes);
        }

        /* Método que irá salvar a alteração, caso a validação do DataAnnotation esteja OK. O campo ID já é bloqueado dentro da View.*/
        [HttpPost]
        public async Task<IActionResult> Edit(Caminhao editar)
        {
            if (ModelState.IsValid)
            {
                _database.Update(editar);
                await _database.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(editar);
        }
        #endregion

#region VIEW DELETE
        public async Task<IActionResult> Delete(int? id) // "id" irá receber o ID do caminhão que cliclamos em Deletar
        {
            var obterDetalhes = await _database.Caminhao.FindAsync(id); // "obterDetalhes" vai armazenar as informações que serão exibidas na view, conforme o valor do parâmetro informado no método FindAsync() 
            return View(obterDetalhes);
        }
        /* Método que irá deletar o caminhão.*/
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var obterDetalhes = await _database.Caminhao.FindAsync(id);
            _database.Caminhao.Remove(obterDetalhes);
            await _database.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        #endregion
    }
}

CRUD/CRUD/Controllers/HomeController.cs
using CRUD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD/CRUD/Views/Caminhao/Create.cshtml
@model CRUD.Models.Caminhao

@{
    ViewData["Title"] = "Criar";
}

<h1>Novo registro</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCaminhao" class="control-label"></label>
                <input asp-for="IdCaminhao" class="form-control" />
                <span asp-validation-for="IdCaminhao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataCriacao" class="control-label"></label>
                <input asp-for="DataCriacao" class="form-control" />
                <span asp-validation-for="DataCriacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUD/CRUD/Views/Caminhao/Delete.cshtml
@model CRUD.Models.Caminhao

@{
    ViewData["Title"] = "Deletar";
}

<h1>Deletar</h1>

<h3>Você tem certeza que deseja deletar esse caminhão?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-10">
            @Html.DisplayNameFor(model => model.IdCaminhao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCaminhao)
        </dd>
        <dt class = "col-sm-10">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-10">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-10">
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para lista</a>
    </form>
</div>

CRUD/CRUD/Views/Caminhao/Details.cshtml
@model CRUD.Models.Caminhao

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-10">
            @Html.DisplayNameFor(model => model.IdCaminhao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCaminhao)
        </dd>
        <dt class = "col-sm-10">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-10">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-10">
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdCaminhao }, new { @class = "btn btn-sm btn-warning" })
    <a asp-action="Index">Voltar para lista</a>
</div>

CRUD/CRUD/Views/Caminhao/Edit.cshtml
@model CRUD.Models.Caminhao

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCaminhao" class="control-label"></label>
                <input asp-for="IdCaminhao" class="form-control" readonly/>
                <span asp-validation-for="IdCaminhao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataCriacao" class="control-label"></label>
                <input asp-for="DataCriacao" class="form-control" />
                <span asp-validation-for="DataCriacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUD/CRUD/Views/Caminhao/Index.cshtml
@model IEnumerable<CRUD.Models.Caminhao>

@{
    ViewData["Title"] = "Caminhões";
}

<h1>Caminhões</h1>

<p>
    <a asp-action="Create" role="button" class="btn btn-primary">Novo Registro</a>
</p>
<table class="table table-hover table-sm">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCriacao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataCriacao)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new {id=item.IdCaminhao}, new { @class="btn btn-sm btn-warning"}) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.IdCaminhao }, new { @class = "btn btn-sm btn-secondary" }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.IdCaminhao }, new { @class = "btn btn-sm btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

CRUD/CRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<h1>Exercício Semana 5 e 6 - CRUD</h1>
<div class="container">
  <p>Um usuário nos informou que necessita realizar um CRUD de caminhões. Após levantamento, temos a seguinte especificação técnica:</p>
  <p class="font-italic">Precisaremos criar uma aplicação Web em C# do tipo ASP.NET Core Web App (Model-View-Controller) na versão 3.1 e sem autenticação;</p>
  <p>A entidade Caminhão terá os seguintes atributos:</p>
  <ul>
    <li>Identificação: número inteiro;</li>
    <li>Nome: string;</li>
    <li>Descrição: string;</li>
    <li>Data de Criação: Data e hora;</li>
  </ul>
  <p>A tela inicial da aplicação deverá listar todos os caminhões cadastrados;</p>
  <p>Os campos para serem apresentados na listagem de caminhões são:</p>
  <ul>
    <li>Nome</li>
    <li>Descrição</li>
    <li>Data de Criação</li>
  </ul>
  <p>Para cada caminhão da lista deve haver 3 botões:</p>
  <ul>
    <li>Editar -> Deve direcionar o usuário para uma tela para editar os campos do caminhão selecionado;</li>
    <li>Detalhes -> Deve direcionar o usuário para uma tela para uma tela para apresentar os detalhes do caminhão selecionado;</li>
    <li>Excluir -> Deve direcionar o usuário para uma tela para uma tela com confirmação para que o usuário possa definir se realmente quer deletar o caminhão selecionado;</li>
  </ul>
  <p>Ainda na tela inicial deve haver um botão para cadastrar um novo caminhão;</p>
  <p>No menu principal da aplicação é necessário um item chamado Caminhões, onde direciona o usuário para a tela de listagem;</p>
</div>

CRUD/CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caminhao" asp-action="Index">Caminhões</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CRUD - Victor Silva
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>